//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 02:55:55 PM CST 
//


package cn.edu.nju.jw.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import cn.edu.nju.schema.个人信息类型;


/**
 * <p>Java class for 学生信息 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="学生信息">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="年级" type="{http://jw.nju.edu.cn/schema}年级类型"/>
 *         &lt;element ref="{http://www.nju.edu.cn/schema}基本信息"/>
 *         &lt;element ref="{http://jw.nju.edu.cn/schema}课程成绩列表"/>
 *       &lt;/all>
 *       &lt;attribute name="学号" type="{http://jw.nju.edu.cn/schema}学号类型" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u5b66\u751f\u4fe1\u606f", propOrder = {

})
public class 学生信息 {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected 年级类型 年级;
    @XmlElement(namespace = "http://www.nju.edu.cn/schema", required = true)
    protected 个人信息类型 基本信息;
    @XmlElement(required = true)
    protected 课程成绩列表类型 课程成绩列表;
    @XmlAttribute
    protected String 学号;

    /**
     * Gets the value of the 年级 property.
     * 
     * @return
     *     possible object is
     *     {@link 年级类型 }
     *     
     */
    public 年级类型 get年级() {
        return 年级;
    }

    /**
     * Sets the value of the 年级 property.
     * 
     * @param value
     *     allowed object is
     *     {@link 年级类型 }
     *     
     */
    public void set年级(年级类型 value) {
        this.年级 = value;
    }

    /**
     * Gets the value of the 基本信息 property.
     * 
     * @return
     *     possible object is
     *     {@link 个人信息类型 }
     *     
     */
    public 个人信息类型 get基本信息() {
        return 基本信息;
    }

    /**
     * Sets the value of the 基本信息 property.
     * 
     * @param value
     *     allowed object is
     *     {@link 个人信息类型 }
     *     
     */
    public void set基本信息(个人信息类型 value) {
        this.基本信息 = value;
    }

    /**
     * Gets the value of the 课程成绩列表 property.
     * 
     * @return
     *     possible object is
     *     {@link 课程成绩列表类型 }
     *     
     */
    public 课程成绩列表类型 get课程成绩列表() {
        return 课程成绩列表;
    }

    /**
     * Sets the value of the 课程成绩列表 property.
     * 
     * @param value
     *     allowed object is
     *     {@link 课程成绩列表类型 }
     *     
     */
    public void set课程成绩列表(课程成绩列表类型 value) {
        this.课程成绩列表 = value;
    }

    /**
     * Gets the value of the 学号 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String get学号() {
        return 学号;
    }

    /**
     * Sets the value of the 学号 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void set学号(String value) {
        this.学号 = value;
    }

}
