//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 02:55:55 PM CST 
//


package cn.edu.nju.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for 个人信息类型 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="个人信息类型">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.nju.edu.cn/schema}个人基本信息类型">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="座机号码" type="{http://www.nju.edu.cn/schema}座机号码类型"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u4e2a\u4eba\u4fe1\u606f\u7c7b\u578b", propOrder = {
    "\u5ea7\u673a\u53f7\u7801"
})
public class 个人信息类型
    extends 个人基本信息类型
{

    protected String 座机号码;

    /**
     * Gets the value of the 座机号码 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String get座机号码() {
        return 座机号码;
    }

    /**
     * Sets the value of the 座机号码 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void set座机号码(String value) {
        this.座机号码 = value;
    }

}
