//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 02:55:55 PM CST 
//


package cn.edu.nju.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for 个人基本信息类型 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="个人基本信息类型">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="姓名" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="性别" type="{http://www.nju.edu.cn/schema}性别类型"/>
 *         &lt;element name="教育背景" type="{http://www.nju.edu.cn/schema}教育类型"/>
 *         &lt;element name="婚姻状况" type="{http://www.nju.edu.cn/schema}婚姻类型"/>
 *         &lt;element name="手机号码" type="{http://www.nju.edu.cn/schema}手机号码类型"/>
 *         &lt;element ref="{http://www.nju.edu.cn/schema}部门"/>
 *         &lt;element name="地址" type="{http://www.nju.edu.cn/schema}地址类型"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u4e2a\u4eba\u57fa\u672c\u4fe1\u606f\u7c7b\u578b", propOrder = {
    "\u59d3\u540d",
    "\u6027\u522b",
    "\u6559\u80b2\u80cc\u666f",
    "\u5a5a\u59fb\u72b6\u51b5",
    "\u624b\u673a\u53f7\u7801",
    "\u90e8\u95e8",
    "\u5730\u5740"
})
@XmlSeeAlso({
    个人信息类型.class
})
public class 个人基本信息类型 {

    @XmlElement(required = true)
    protected String 姓名;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected 性别类型 性别;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected 教育类型 教育背景;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected 婚姻类型 婚姻状况;
    @XmlElement(required = true)
    protected String 手机号码;
    @XmlElement(required = true)
    protected 部门类型 部门;
    @XmlElement(required = true)
    protected 地址类型 地址;

    /**
     * Gets the value of the 姓名 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String get姓名() {
        return 姓名;
    }

    /**
     * Sets the value of the 姓名 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void set姓名(String value) {
        this.姓名 = value;
    }

    /**
     * Gets the value of the 性别 property.
     * 
     * @return
     *     possible object is
     *     {@link 性别类型 }
     *     
     */
    public 性别类型 get性别() {
        return 性别;
    }

    /**
     * Sets the value of the 性别 property.
     * 
     * @param value
     *     allowed object is
     *     {@link 性别类型 }
     *     
     */
    public void set性别(性别类型 value) {
        this.性别 = value;
    }

    /**
     * Gets the value of the 教育背景 property.
     * 
     * @return
     *     possible object is
     *     {@link 教育类型 }
     *     
     */
    public 教育类型 get教育背景() {
        return 教育背景;
    }

    /**
     * Sets the value of the 教育背景 property.
     * 
     * @param value
     *     allowed object is
     *     {@link 教育类型 }
     *     
     */
    public void set教育背景(教育类型 value) {
        this.教育背景 = value;
    }

    /**
     * Gets the value of the 婚姻状况 property.
     * 
     * @return
     *     possible object is
     *     {@link 婚姻类型 }
     *     
     */
    public 婚姻类型 get婚姻状况() {
        return 婚姻状况;
    }

    /**
     * Sets the value of the 婚姻状况 property.
     * 
     * @param value
     *     allowed object is
     *     {@link 婚姻类型 }
     *     
     */
    public void set婚姻状况(婚姻类型 value) {
        this.婚姻状况 = value;
    }

    /**
     * Gets the value of the 手机号码 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String get手机号码() {
        return 手机号码;
    }

    /**
     * Sets the value of the 手机号码 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void set手机号码(String value) {
        this.手机号码 = value;
    }

    /**
     * Gets the value of the 部门 property.
     * 
     * @return
     *     possible object is
     *     {@link 部门类型 }
     *     
     */
    public 部门类型 get部门() {
        return 部门;
    }

    /**
     * Sets the value of the 部门 property.
     * 
     * @param value
     *     allowed object is
     *     {@link 部门类型 }
     *     
     */
    public void set部门(部门类型 value) {
        this.部门 = value;
    }

    /**
     * Gets the value of the 地址 property.
     * 
     * @return
     *     possible object is
     *     {@link 地址类型 }
     *     
     */
    public 地址类型 get地址() {
        return 地址;
    }

    /**
     * Sets the value of the 地址 property.
     * 
     * @param value
     *     allowed object is
     *     {@link 地址类型 }
     *     
     */
    public void set地址(地址类型 value) {
        this.地址 = value;
    }

}
