//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 02:55:55 PM CST 
//


package cn.edu.nju.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for 婚姻类型.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="婚姻类型">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="未婚"/>
 *     &lt;enumeration value="已婚"/>
 *     &lt;enumeration value="离异"/>
 *     &lt;enumeration value="丧偶"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "\u5a5a\u59fb\u7c7b\u578b")
@XmlEnum
public enum 婚姻类型 {

    未婚,
    已婚,
    离异,
    丧偶;

    public String value() {
        return name();
    }

    public static 婚姻类型 fromValue(String v) {
        return valueOf(v);
    }

}
