//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 02:55:55 PM CST 
//


package cn.edu.nju.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for 部门类型 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="部门类型">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="部门主管" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="部门描述" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *       &lt;attribute name="部门属性" type="{http://www.nju.edu.cn/schema}部门属性类型" />
 *       &lt;attribute name="部门编号" type="{http://www.nju.edu.cn/schema}部门编号类型" />
 *       &lt;attribute name="部门名称" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "\u90e8\u95e8\u7c7b\u578b", propOrder = {

})
public class 部门类型 {

    @XmlElement(required = true)
    protected String 部门主管;
    @XmlElement(required = true)
    protected String 部门描述;
    @XmlAttribute
    protected 部门属性类型 部门属性;
    @XmlAttribute
    protected String 部门编号;
    @XmlAttribute
    protected String 部门名称;

    /**
     * Gets the value of the 部门主管 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String get部门主管() {
        return 部门主管;
    }

    /**
     * Sets the value of the 部门主管 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void set部门主管(String value) {
        this.部门主管 = value;
    }

    /**
     * Gets the value of the 部门描述 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String get部门描述() {
        return 部门描述;
    }

    /**
     * Sets the value of the 部门描述 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void set部门描述(String value) {
        this.部门描述 = value;
    }

    /**
     * Gets the value of the 部门属性 property.
     * 
     * @return
     *     possible object is
     *     {@link 部门属性类型 }
     *     
     */
    public 部门属性类型 get部门属性() {
        return 部门属性;
    }

    /**
     * Sets the value of the 部门属性 property.
     * 
     * @param value
     *     allowed object is
     *     {@link 部门属性类型 }
     *     
     */
    public void set部门属性(部门属性类型 value) {
        this.部门属性 = value;
    }

    /**
     * Gets the value of the 部门编号 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String get部门编号() {
        return 部门编号;
    }

    /**
     * Sets the value of the 部门编号 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void set部门编号(String value) {
        this.部门编号 = value;
    }

    /**
     * Gets the value of the 部门名称 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String get部门名称() {
        return 部门名称;
    }

    /**
     * Sets the value of the 部门名称 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void set部门名称(String value) {
        this.部门名称 = value;
    }

}
