//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.30 at 02:55:55 PM CST 
//


package cn.edu.nju.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for 部门属性类型.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="部门属性类型">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="系"/>
 *     &lt;enumeration value="院"/>
 *     &lt;enumeration value="直属"/>
 *     &lt;enumeration value="行政部门"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "\u90e8\u95e8\u5c5e\u6027\u7c7b\u578b")
@XmlEnum
public enum 部门属性类型 {

    系,
    院,
    直属,
    行政部门;

    public String value() {
        return name();
    }

    public static 部门属性类型 fromValue(String v) {
        return valueOf(v);
    }

}
